### ISSUE TITLE
`fix-macho.rb` requires sudo during `build.ts`

### ISSUE THREAD

**Issue by mxcl** [teaxyz/pantry.core#18]
Bundler apparently think this is “working as intended” 🤨

https://github.com/rubygems/rubygems/issues/3230

**Comment by jhheider** [comment]
hm, how does one trigger this requirement? adding `$TEA_PREFIX/tea.xyz/var/pantry/scripts/brewkit/fix-machos.rb .` to a random build script causes no issues for me.

**Comment by mxcl** [comment]
you have to clear out your gems first I think. In all locations.

Potentially clean install? Lol

**Comment by magnusviri** [comment]
Instead of doing a clean install, consider using a VM. If you're on ARM, I highly recommend [tart](https://github.com/cirruslabs/tart) on Mac Mini's or [Anka](https://veertu.com/) on laptops (tart isn't as full-featured as Anka, but the Anka free license won't run on a Mac Mini). There are a lot of other virtualization solutions but it seems to me that tart and Anka are the most tailored for developers and ci/cd.

**Comment by lino-levan** [comment]
This is blocking https://github.com/teaxyz/pantry.extra/issues/334 (afaik, I'm going to be honest I'm not great at packaging yet, but I'd love to get better) which is apparently blocking https://github.com/teaxyz/pantry.extra/issues/336

**Comment by mxcl** [comment]
Fixed by setting `GEM_HOME` to somewhere we control.

**Comment by mxcl** [comment]
you'll need to upgrade brew kit: `tea -SE` in pantry or `tea -S tea.xyz/brewkit` otherwise
